### ISSUE TITLE
Game crashes when moving card outside the screen

### ISSUE THREAD

**Issue by alcalyn** [schotten-totten-company/schotten-totten#67]
I can reproduce it often but not consistently:

- Start a new game vs IA
- Move a card on the board
- At the next turn, drag a card and drop it at the side of the screen so that it's like it drops outside

I expect the card just go back to its initial position, but instead the game crashes.

I'm on Fairphone 3, android 9, `SchottenTotten_43.apk` from github releases.

**Comment by bastienbarthet** [comment]
Thank you for your detailed description of the issue.
I am also able to reproduce the crash.
I will fix it as soon as possible.
Do not hesitate to open other issues if you find anything else wrong.
As this app has only be tested by few people, many bugs are probably still there.

**Comment by bastienbarthet** [comment]
issue corrected in v4.4 release
